// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 暴露给前端的入口，负责配置读写、网关生命周期和桌面交互。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BindThread 把网关当前线程切换到指定会话。
 * @param {string} threadID
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function BindThread(threadID) {
    return $Call.ByID(3808863474, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ConnectionURL 根据当前配置生成手机端连接地址。
 * @param {string} host
 * @returns {$CancellablePromise<string>}
 */
export function ConnectionURL(host) {
    return $Call.ByID(2375271090, host);
}

/**
 * DetectCodexBinary 自动查找本机 Codex 可执行文件。
 * @param {string} input
 * @returns {$CancellablePromise<string>}
 */
export function DetectCodexBinary(input) {
    return $Call.ByID(4033048004, input);
}

/**
 * GenerateToken 生成 32 字节随机 token，用于手机端连接鉴权。
 * @returns {$CancellablePromise<string>}
 */
export function GenerateToken() {
    return $Call.ByID(4289815263);
}

/**
 * GetConfig 返回当前配置和状态快照。
 * @returns {$CancellablePromise<$models.AppSnapshot>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * HealthCheck 返回网关、Codex app-server 和当前线程状态。
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function HealthCheck() {
    return $Call.ByID(1288635913).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListLogDays 返回已有日志日期，供前端日志选项卡选择。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListLogDays() {
    return $Call.ByID(1295584698).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListThreads 读取当前工作目录下的 Codex 线程列表。
 * @returns {$CancellablePromise<$models.ThreadSummary[]>}
 */
export function ListThreads() {
    return $Call.ByID(1090132042).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * QuitApp 从托盘菜单退出应用。
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * ReadLogEntries 读取指定日期和类型的最新 50 条日志。
 * @param {string} day
 * @param {string} kind
 * @returns {$CancellablePromise<$models.LogEntry[]>}
 */
export function ReadLogEntries(day, kind) {
    return $Call.ByID(2878607551, day, kind).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SaveConfig 保存配置；工作目录变化且网关运行时自动重启，让手机端重连后拿到新目录。
 * @param {$models.AppConfig} cfg
 * @returns {$CancellablePromise<$models.AppSnapshot>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SelectWorkspace 打开系统目录选择框，并返回用户选择的工作目录。
 * @returns {$CancellablePromise<string>}
 */
export function SelectWorkspace() {
    return $Call.ByID(968537718);
}

/**
 * ShortPath 返回用于界面显示的短路径，完整路径仍保存在配置中。
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ShortPath(path) {
    return $Call.ByID(1382795886, path);
}

/**
 * ShowWindow 从托盘菜单恢复主窗口。
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * StartGateway 启动本机 Codex Mobile Gateway。
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function StartGateway() {
    return $Call.ByID(1858695823).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StopGateway 停止本机 Codex Mobile Gateway。
 * @returns {$CancellablePromise<$models.GatewayStatus>}
 */
export function StopGateway() {
    return $Call.ByID(2175675921).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GatewayStatus.createFrom;
const $$createType1 = $models.AppSnapshot.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.ThreadSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.LogEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
