// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig 是桌面网关持久化配置，字段保持简单以方便迁移和手动排查。
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspace"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("codexBinary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codexBinary"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("codexHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codexHost"] = "";
        }
        if (!("codexPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["codexPort"] = 0;
        }
        if (!("boundThreadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["boundThreadId"] = "";
        }
        if (!("clientPingIntervalMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clientPingIntervalMs"] = 0;
        }
        if (!("clientIdleTimeoutMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clientIdleTimeoutMs"] = 0;
        }
        if (!("lastConnectionBaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastConnectionBaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * AppSnapshot 是前端初始化需要的一次性状态。
 */
export class AppSnapshot {
    /**
     * Creates a new AppSnapshot instance.
     * @param {Partial<AppSnapshot>} [$$source = {}] - The source object to create the AppSnapshot.
     */
    constructor($$source = {}) {
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {AppConfig}
             */
            this["config"] = (new AppConfig());
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {GatewayStatus}
             */
            this["status"] = (new GatewayStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new AppSnapshot(/** @type {Partial<AppSnapshot>} */($$parsedSource));
    }
}

/**
 * GatewayStatus 是桌面配置页和健康检查使用的网关状态。
 */
export class GatewayStatus {
    /**
     * Creates a new GatewayStatus instance.
     * @param {Partial<GatewayStatus>} [$$source = {}] - The source object to create the GatewayStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("appServer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appServer"] = "";
        }
        if (!("threadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["threadId"] = "";
        }
        if (!("defaultThreadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultThreadId"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("activeTurnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeTurnId"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("httpRestartCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpRestartCount"] = 0;
        }
        if (!("appServerRestartCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appServerRestartCount"] = 0;
        }
        if (!("appServerRestarting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["appServerRestarting"] = false;
        }
        if (!("appServerNextRestart" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appServerNextRestart"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayStatus(/** @type {Partial<GatewayStatus>} */($$parsedSource));
    }
}

/**
 * ThreadSummary 是桌面 App 和手机端共享的线程列表条目。
 */
export class ThreadSummary {
    /**
     * Creates a new ThreadSummary instance.
     * @param {Partial<ThreadSummary>} [$$source = {}] - The source object to create the ThreadSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadSummary(/** @type {Partial<ThreadSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AppConfig.createFrom;
const $$createType1 = GatewayStatus.createFrom;
