// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindThread(arg1) {
  return window['go']['main']['App']['BindThread'](arg1);
}

export function ConnectionURL(arg1) {
  return window['go']['main']['App']['ConnectionURL'](arg1);
}

export function GenerateToken() {
  return window['go']['main']['App']['GenerateToken']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function ShortPath(arg1) {
  return window['go']['main']['App']['ShortPath'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}
