// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BindThread(arg1:string):Promise<main.GatewayStatus>;

export function ConnectionURL(arg1:string):Promise<string>;

export function GenerateToken():Promise<string>;

export function GetConfig():Promise<main.AppSnapshot>;

export function HealthCheck():Promise<main.GatewayStatus>;

export function ListThreads():Promise<Array<main.ThreadSummary>>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.AppSnapshot>;

export function SelectWorkspace():Promise<string>;

export function ShortPath(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartGateway():Promise<main.GatewayStatus>;

export function StopGateway():Promise<main.GatewayStatus>;
